name: graphula
version: "0.1.0"
maintainer: Front Row Education

extra-source-files:
  - stack.yaml

dependencies:
  - aeson
  - base
  - bytestring
  - directory
  - exceptions
  - free
  - HUnit
  - mtl
  - persistent
  - QuickCheck
  - temporary
  - transformers

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  fansible:
    main: Example.hs
    ghc-options: -Wall
    dependencies:
      - base
      - graphula

tests:
  test:
    source-dirs:
      - test
    main: Spec.hs
    dependencies:
      - base
      - graphula
      - persistent
      - persistent-template
      - persistent-sqlite
      - hspec
