name: graphula
version: "0.1.0"
maintainer: Front Row Education

extra-source-files:
  - ../stack.yaml

dependencies:
  - aeson
  - base
  - bytestring
  - directory
  - exceptions
  - free
  - generics-eot
  - HUnit
  - mtl
  - QuickCheck
  - temporary
  - transformers

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  fansible:
    main: README.lhs
    ghc-options: -Wall -pgmL markdown-unlit
    dependencies:
      - base
      - graphula
      - markdown-unlit
